name: Run Python Script
run-name: ${{ github.actor }} is testing out running a python script through GitHub Actions 🚀
on: [push]

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone Team-Bathysphere Research Repository (Test Branch)
      run: |
        git clone --branch test-GitHub-API https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/Team-Bathysphere/research.git research-repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the desired Python versionß
    - name: Install Dependencies
      run: |
        cd research-repo
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: |
        cd research-repo
        python ben/github-api-testing.py