# Put this file in a different GitHub repo to spin up Action runnners which will execute the docker-comnpose of the language parser
name: Run Python Script
run-name: ${{ github.actor }} is testing out running a python script through GitHub Actions 🚀
on: [push]

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone Team-Bathysphere Research Repository (Test Branch)
      run: |
        git clone --branch test-GitHub-API https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/Team-Bathysphere/research.git research-repo

    # TODO clean this up for branch arguments
    # You need to add an open_AI key and git token in the remote repository
    - name: Run Neo4j and parse the files
      run: |
        cd research-repo/jerry/language-server-protocol-py
        REPO_AUTHOR=flpymonkey REPO_NAME=AlgoFinal MAIN_BRANCH=main CHANGE_BRANCH=${{ github.ref_name }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} docker-compose up --build
        