name: Run Python Script
run-name: ${{ github.actor }} is testing out running a python script through GitHub Actions 🚀
on: [push]

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone Team-Bathysphere Research Repository (Test Branch)
      run: |
        git clone --branch test-GitHub-API https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/Team-Bathysphere/research.git research-repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the desired Python versionß
    - name: Install Dependencies
      run: |
        cd research-repo
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Pull the contents of this repo to the runner for language parsing
    # TODO -- put the name and owner of your repo here, generalize this
    - name: Run Python Script - repo pull
      run: |
        cd research-repo
        python ben/pull-repo-contents.py flpymonkey AlgoFinal

    - name: Start Neo4j with Docker Compose
      run: |
        cd research-repo/jerry/neo4j
        docker-compose up -d

    # TODO fix this, wait a sec for neo4j to come up
    - name: Wait
      run: sleep 10  # waits for 10 seconds

    # TODO pass in the pulled repo name and parse the files
    - name: Run Python Script - Parse files
      run: |
        cd research-repo
        python jerry/language-server-protocol-py/parse.py ./AlgoFinal